const canvas = document.querySelector('#game-canvas');
const ctx = canvas.getContext('2d');
const W = canvas.width, H = canvas.height;
const keys = new Set();
const colors = { aqua: '#54e0c0', orange: '#ffad57', red: '#ff657c', ice: '#d9f2ed', terrain: '#163844', terrainLight: '#1d5260' };
let state = 'ready', score = 0, highScore = Number(localStorage.getItem('skyraid-high-score') || 0), wave = 1, armor = 5, scroll = 0, spawnTimer = 0, groundTimer = 0, powerupTimer = 0, lastTime = 0, flash = 0, boss = null, bossWave = 0, weaponLevel = 1;
const player = { x: W / 2, y: H - 95, speed: 270, cooldown: 0, fireRate: .16, bombCooldown: 0, bombStock: 3, invincible: 0 };
const bullets = [], bombs = [], enemies = [], targets = [], particles = [], powerups = [];
const hud = { score: document.querySelector('#score'), high: document.querySelector('#high-score'), wave: document.querySelector('#wave'), armor: document.querySelector('#armor'), air: document.querySelector('#air-ammo'), ground: document.querySelector('#ground-ammo'), upgrade: document.querySelector('#upgrade-level'), upgradeName: document.querySelector('#upgrade-name'), status: document.querySelector('#mission-status') };
hud.high.textContent = String(highScore).padStart(6, '0');

function resetGame() { score = 0; wave = 1; armor = 5; weaponLevel = 1; boss = null; bossWave = 0; scroll = 0; spawnTimer = 0; groundTimer = 0; powerupTimer = 0; bullets.length = 0; bombs.length = 0; enemies.length = 0; targets.length = 0; particles.length = 0; powerups.length = 0; player.x = W / 2; player.y = H - 95; player.cooldown = 0; player.fireRate = .16; player.bombCooldown = 0; player.bombStock = 3; player.invincible = 0; state = 'playing'; hud.status.textContent = 'MISSION ACTIVE'; updateHud(); }
function updateHud() { hud.score.textContent = String(score).padStart(6, '0'); hud.high.textContent = String(Math.max(highScore, score)).padStart(6, '0'); hud.wave.textContent = String(wave).padStart(2, '0'); hud.ground.textContent = String(player.bombStock).padStart(2, '0'); hud.upgrade.textContent = String(weaponLevel).padStart(2, '0'); hud.upgradeName.textContent = weaponLevel === 1 ? 'STANDARD' : weaponLevel === 2 ? 'DUAL CANNON' : 'TRIPLE CANNON'; [...hud.armor.children].forEach((item, index) => item.classList.toggle('off', index >= armor)); }
function addScore(points) { score += points; if (score > highScore) { highScore = score; localStorage.setItem('skyraid-high-score', highScore); } updateHud(); }
function startGame() { document.querySelector('#start-screen').classList.add('hidden'); document.querySelector('#game-over-screen').classList.add('hidden'); resetGame(); }
function pauseGame() { if (state === 'playing') { state = 'paused'; document.querySelector('#pause-screen').classList.remove('hidden'); hud.status.textContent = 'SYSTEM PAUSED'; } else if (state === 'paused') { resumeGame(); } }
function resumeGame() { state = 'playing'; document.querySelector('#pause-screen').classList.add('hidden'); hud.status.textContent = 'MISSION ACTIVE'; }
function endGame() { state = 'over'; document.querySelector('#final-score').textContent = `최종 점수 ${String(score).padStart(6, '0')}`; document.querySelector('#game-over-screen').classList.remove('hidden'); hud.status.textContent = 'SIGNAL LOST'; }
function shoot() { if (player.cooldown > 0 || state !== 'playing') return; const offsets = weaponLevel === 1 ? [0] : weaponLevel === 2 ? [-8, 8] : [-12, 0, 12]; offsets.forEach(offset => bullets.push({ x: player.x + offset, y: player.y - 24, speed: 450, drift: offset * .03 })); player.cooldown = player.fireRate; }
function bomb() { if (player.bombCooldown > 0 || player.bombStock <= 0 || state !== 'playing') return; bombs.push({ x: player.x, y: player.y - 10, radius: 5, speed: 240 }); player.bombCooldown = 2.2; player.bombStock--; updateHud(); }
function spawnEnemy() { const type = Math.random() > .77 ? 'ace' : 'drone'; enemies.push({ x: 35 + Math.random() * (W - 70), y: -30, speed: 50 + Math.random() * 45 + wave * 2, type, phase: Math.random() * Math.PI * 2, hp: type === 'ace' ? 2 : 1, fire: 1.5 + Math.random() * 2 }); }
function spawnTarget() { targets.push({ x: 35 + Math.random() * (W - 70), y: -25, speed: 33 + wave, hp: 1, size: 12 }); }
function spawnPowerup(x = 35 + Math.random() * (W - 70), y = -20, forcedType = null) { const types = ['spread', 'shield', 'rapid', 'bomb']; const type = forcedType || types[Math.floor(Math.random() * types.length)]; powerups.push({ x, y, speed: 42, type, size: 13, phase: Math.random() * Math.PI * 2 }); }
function spawnBoss() { boss = { x: W / 2, y: -65, hp: 28 + wave * 3, maxHp: 28 + wave * 3, fire: 1.2, phase: 0 }; enemies.length = 0; targets.length = 0; hud.status.textContent = 'BOSS INBOUND'; }
function collectPowerup(item) { item.dead = true; createExplosion(item.x, item.y, colors.aqua, 12); if (item.type === 'spread') weaponLevel = Math.min(3, weaponLevel + 1); if (item.type === 'shield') armor = Math.min(5, armor + 1); if (item.type === 'rapid') player.fireRate = Math.max(.07, player.fireRate - .03); if (item.type === 'bomb') player.bombStock = Math.min(9, player.bombStock + 2); addScore(50); updateHud(); }
function createExplosion(x, y, color, amount = 10) { for (let i = 0; i < amount; i++) particles.push({ x, y, dx: (Math.random() - .5) * 150, dy: (Math.random() - .5) * 150, life: .4 + Math.random() * .5, color }); }
function hitPlayer() { if (player.invincible > 0) return; armor--; player.invincible = 1.5; flash = .22; createExplosion(player.x, player.y, colors.red, 15); updateHud(); if (armor <= 0) endGame(); }
function distance(a, b) { return Math.hypot(a.x - b.x, a.y - b.y); }
function update(dt) {
  if (state !== 'playing') return;
  scroll = (scroll + 45 * dt) % 60; player.cooldown -= dt; player.bombCooldown -= dt; player.invincible -= dt; flash -= dt;
  const moveX = (keys.has('arrowright') || keys.has('d') ? 1 : 0) - (keys.has('arrowleft') || keys.has('a') ? 1 : 0); const moveY = (keys.has('arrowdown') || keys.has('s') ? 1 : 0) - (keys.has('arrowup') || keys.has('w') ? 1 : 0);
  player.x = Math.max(22, Math.min(W - 22, player.x + moveX * player.speed * dt)); player.y = Math.max(H * .52, Math.min(H - 35, player.y + moveY * player.speed * dt));
  if (keys.has(' ') || keys.has('j')) shoot(); if (keys.has('x') || keys.has('k')) bomb();
  spawnTimer += dt; groundTimer += dt; powerupTimer += dt;
  if (wave % 5 === 0 && bossWave !== wave && !boss) { spawnBoss(); bossWave = wave; }
  if (!boss && spawnTimer > Math.max(.35, 1.1 - wave * .04)) { spawnEnemy(); spawnTimer = 0; }
  if (!boss && groundTimer > 2.4) { spawnTarget(); groundTimer = 0; }
  if (!boss && powerupTimer > 9) { spawnPowerup(); powerupTimer = 0; }
  bullets.forEach(item => { item.y -= item.speed * dt; item.x += (item.drift || 0) * 450 * dt; }); bombs.forEach(item => { item.y -= item.speed * dt; item.radius += 80 * dt; }); enemies.forEach(item => { item.y += item.speed * dt; item.x += Math.sin(item.y * .02 + item.phase) * 35 * dt; item.fire -= dt; }); targets.forEach(item => item.y += item.speed * dt); powerups.forEach(item => { item.y += item.speed * dt; item.x += Math.sin(item.y * .03 + item.phase) * 18 * dt; });
  if (boss) { boss.y = Math.min(105, boss.y + 55 * dt); boss.phase += dt; boss.x = W / 2 + Math.sin(boss.phase * .8) * 145; boss.fire -= dt; if (boss.fire < 0) { boss.fire = .8; for (let i = -1; i <= 1; i++) bullets.push({ x: boss.x + i * 20, y: boss.y + 30, speed: -190, enemy: true }); } }
  for (const item of enemies) if (item.fire < 0) { item.fire = 3; bullets.push({ x: item.x, y: item.y + 18, speed: -180, enemy: true }); }
  for (const bullet of bullets) { if (bullet.enemy) { bullet.y += Math.abs(bullet.speed) * dt; if (distance(bullet, player) < 19) { bullet.y = H + 50; hitPlayer(); } } }
  for (const bullet of bullets) { if (bullet.enemy) continue; for (const enemy of enemies) if (distance(bullet, enemy) < 22) { bullet.y = -50; enemy.hp--; createExplosion(enemy.x, enemy.y, colors.red, 5); if (enemy.hp <= 0) { enemy.dead = true; addScore(enemy.type === 'ace' ? 250 : 100); if (Math.random() < .16) spawnPowerup(enemy.x, enemy.y); } } if (boss && distance(bullet, boss) < 42) { bullet.y = -50; boss.hp--; createExplosion(boss.x, boss.y, colors.orange, 2); if (boss.hp <= 0) { addScore(1200); createExplosion(boss.x, boss.y, colors.orange, 45); spawnPowerup(boss.x, boss.y, 'spread'); spawnPowerup(boss.x - 22, boss.y, 'shield'); boss = null; hud.status.textContent = 'BOSS DESTROYED'; } } }
  for (const dropped of bombs) { for (const target of targets) if (distance(dropped, target) < dropped.radius + target.size) { dropped.y = -80; target.dead = true; addScore(150); createExplosion(target.x, target.y, colors.orange, 12); } if (boss && distance(dropped, boss) < dropped.radius + 35) { dropped.y = -80; boss.hp -= 3; createExplosion(boss.x, boss.y, colors.orange, 8); } }
  for (const item of powerups) if (distance(item, player) < item.size + 18) collectPowerup(item);
  for (const enemy of enemies) if (distance(enemy, player) < 26) { enemy.dead = true; hitPlayer(); }
  [...enemies, ...targets, ...powerups].forEach(item => { if (item.y > H + 40) item.dead = true; });
  bullets.splice(0, bullets.length, ...bullets.filter(item => item.y > -50 && item.y < H + 50)); bombs.splice(0, bombs.length, ...bombs.filter(item => item.y > -50)); enemies.splice(0, enemies.length, ...enemies.filter(item => !item.dead)); targets.splice(0, targets.length, ...targets.filter(item => !item.dead)); powerups.splice(0, powerups.length, ...powerups.filter(item => !item.dead));
  particles.forEach(item => { item.x += item.dx * dt; item.y += item.dy * dt; item.life -= dt; }); particles.splice(0, particles.length, ...particles.filter(item => item.life > 0)); wave = Math.floor(score / 1500) + 1; updateHud();
}
function drawBackground() { ctx.fillStyle = '#081b25'; ctx.fillRect(0, 0, W, H); ctx.fillStyle = colors.terrain; for (let y = -60 + scroll; y < H; y += 60) { ctx.fillRect(0, y, W, 2); ctx.fillStyle = colors.terrainLight; for (let x = (y % 120) - 45; x < W; x += 90) { ctx.beginPath(); ctx.moveTo(x, y + 15); ctx.lineTo(x + 27, y + 4); ctx.lineTo(x + 52, y + 15); ctx.lineTo(x + 27, y + 27); ctx.fill(); } ctx.fillStyle = colors.terrain; } ctx.strokeStyle = 'rgba(84,224,192,.08)'; for (let x = 15; x < W; x += 30) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); } }
function drawPlayer() { if (player.invincible > 0 && Math.floor(player.invincible * 12) % 2 === 0) return; ctx.save(); ctx.translate(player.x, player.y); ctx.fillStyle = colors.aqua; ctx.beginPath(); ctx.moveTo(0, -25); ctx.lineTo(19, 18); ctx.lineTo(6, 14); ctx.lineTo(0, 23); ctx.lineTo(-6, 14); ctx.lineTo(-19, 18); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#e9fff7'; ctx.beginPath(); ctx.moveTo(0, -14); ctx.lineTo(6, 5); ctx.lineTo(-6, 5); ctx.closePath(); ctx.fill(); ctx.fillStyle = colors.orange; ctx.fillRect(-4, 16, 8, 7); ctx.restore(); }
function drawEntities() { bullets.forEach(item => { ctx.fillStyle = item.enemy ? colors.red : colors.ice; ctx.fillRect(item.x - 2, item.y - 9, 4, 18); }); bombs.forEach(item => { ctx.fillStyle = colors.orange; ctx.beginPath(); ctx.arc(item.x, item.y, 5, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = 'rgba(255,173,87,.3)'; ctx.beginPath(); ctx.arc(item.x, item.y, item.radius, 0, Math.PI * 2); ctx.stroke(); }); enemies.forEach(item => { ctx.save(); ctx.translate(item.x, item.y); ctx.fillStyle = item.type === 'ace' ? colors.red : '#e66c78'; ctx.beginPath(); ctx.moveTo(0, -17); ctx.lineTo(20, 10); ctx.lineTo(7, 7); ctx.lineTo(0, 17); ctx.lineTo(-7, 7); ctx.lineTo(-20, 10); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#ffc2b9'; ctx.fillRect(-3, -3, 6, 8); ctx.restore(); }); targets.forEach(item => { ctx.fillStyle = colors.orange; ctx.fillRect(item.x - 12, item.y - 8, 24, 16); ctx.fillStyle = '#613e2c'; ctx.fillRect(item.x - 5, item.y - 5, 10, 10); }); powerups.forEach(item => { const icon = { spread: 'S', shield: '+', rapid: 'R', bomb: 'B' }[item.type]; const color = item.type === 'shield' ? colors.aqua : item.type === 'bomb' ? colors.orange : colors.ice; ctx.save(); ctx.translate(item.x, item.y); ctx.rotate(Math.PI / 4); ctx.fillStyle = 'rgba(84,224,192,.2)'; ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.fillRect(-12, -12, 24, 24); ctx.strokeRect(-12, -12, 24, 24); ctx.rotate(-Math.PI / 4); ctx.fillStyle = color; ctx.font = 'bold 15px Space Mono'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(icon, 0, 1); ctx.restore(); }); if (boss) { ctx.save(); ctx.translate(boss.x, boss.y); ctx.fillStyle = '#a53558'; ctx.beginPath(); ctx.moveTo(0, -34); ctx.lineTo(48, 20); ctx.lineTo(19, 17); ctx.lineTo(0, 36); ctx.lineTo(-19, 17); ctx.lineTo(-48, 20); ctx.closePath(); ctx.fill(); ctx.fillStyle = colors.orange; ctx.fillRect(-8, -8, 16, 19); ctx.fillStyle = '#ffb8c2'; ctx.fillRect(-3, -3, 6, 8); ctx.restore(); ctx.fillStyle = '#27313a'; ctx.fillRect(65, 28, W - 130, 7); ctx.fillStyle = colors.red; ctx.fillRect(65, 28, (W - 130) * Math.max(0, boss.hp / boss.maxHp), 7); ctx.fillStyle = colors.ice; ctx.font = 'bold 10px Space Mono'; ctx.textAlign = 'center'; ctx.fillText('BOSS // AERIAL FORTRESS', W / 2, 20); } particles.forEach(item => { ctx.globalAlpha = Math.max(0, item.life * 1.5); ctx.fillStyle = item.color; ctx.fillRect(item.x - 2, item.y - 2, 4, 4); ctx.globalAlpha = 1; }); }
function draw() { drawBackground(); drawEntities(); drawPlayer(); if (flash > 0) { ctx.fillStyle = `rgba(255,101,124,${flash * 2})`; ctx.fillRect(0, 0, W, H); } }
function frame(time = 0) { const dt = Math.min(.05, (time - lastTime) / 1000); lastTime = time; update(dt); draw(); requestAnimationFrame(frame); }
window.addEventListener('keydown', event => { const key = event.key === ' ' ? ' ' : event.key.toLowerCase(); keys.add(key); if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', ' '].includes(event.key)) event.preventDefault(); if (key === 'enter' && state === 'ready') startGame(); if (key === 'p') pauseGame(); if (key === 'r' && state === 'over') startGame(); }); window.addEventListener('keyup', event => keys.delete(event.key === ' ' ? ' ' : event.key.toLowerCase()));
document.querySelector('#start-button').addEventListener('click', startGame); document.querySelector('#restart-button').addEventListener('click', startGame); document.querySelector('#resume-button').addEventListener('click', resumeGame);
document.querySelectorAll('[data-control]').forEach(button => { const action = button.dataset.control; button.addEventListener('pointerdown', () => { if (action === 'left') keys.add('a'); if (action === 'right') keys.add('d'); if (action === 'fire') keys.add('j'); if (action === 'bomb') keys.add('x'); }); button.addEventListener('pointerup', () => { keys.delete('a'); keys.delete('d'); keys.delete('j'); keys.delete('x'); }); });
requestAnimationFrame(frame);
